default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  port: 5432

development:
  <<: *default
  database: 'dashboard_development'
  username: 'askalon'
  password: 'dashboard_development'
  host: localhost

test:
  <<: *default
  database: 'dashboard_test'
  username: 'askalon'
  password: 'dashboard_test'
  host: localhost

production:
  <<: *default
  database: 'dashboard_prod'
  username: 'askalon'
  password: <%= ENV['DB_PASSWORD'] %>
